[package]
name = "bicit-cli"
version = "0.3.0"
authors = ["Luca Ognibene <luca.ognibene@gmail.com>"]
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
anyhow = "1.0.100"
bicit = { version = "0.1.0", path = "../bicit" }
